// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/manga_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manga represents a manga entry
type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_proto_manga_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// UserProgress represents user reading progress
type UserProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_proto_manga_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UserProgress) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *UserProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserProgress) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetMangaRequest for UC-014: Retrieve Manga via gRPC
type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_proto_manga_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

// GetMangaResponse for UC-014
type GetMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaResponse) Reset() {
	*x = GetMangaResponse{}
	mi := &file_proto_manga_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaResponse) ProtoMessage() {}

func (x *GetMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaResponse.ProtoReflect.Descriptor instead.
func (*GetMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

// SearchMangaRequest for UC-015: Search Manga via gRPC
type SearchMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`   // Optional: search in title/author
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`   // Optional: filter by genre
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Optional: filter by status
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`    // Page number (default: 1)
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`  // Results per page (default: 20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaRequest) Reset() {
	*x = SearchMangaRequest{}
	mi := &file_proto_manga_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaRequest) ProtoMessage() {}

func (x *SearchMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaRequest.ProtoReflect.Descriptor instead.
func (*SearchMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMangaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMangaRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SearchMangaRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchMangaResponse for UC-015
type SearchMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Manga               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaResponse) Reset() {
	*x = SearchMangaResponse{}
	mi := &file_proto_manga_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaResponse) ProtoMessage() {}

func (x *SearchMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaResponse.ProtoReflect.Descriptor instead.
func (*SearchMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchMangaResponse) GetData() []*Manga {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchMangaResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchMangaResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMangaResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchMangaResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// UpdateProgressRequest for UC-016: Update Progress via gRPC
type UpdateProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Optional: "reading", "completed", "on_hold", etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_manga_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpdateProgressRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *UpdateProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateProgressResponse for UC-016
type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BroadcastSent bool                   `protobuf:"varint,3,opt,name=broadcast_sent,json=broadcastSent,proto3" json:"broadcast_sent,omitempty"` // Whether TCP broadcast was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_proto_manga_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProgressResponse) GetBroadcastSent() bool {
	if x != nil {
		return x.BroadcastSent
	}
	return false
}

var File_proto_manga_service_proto protoreflect.FileDescriptor

const file_proto_manga_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/manga_service.proto\x12\bmangahub\"\xdb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"\xa2\x01\n" +
	"\fUserProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\",\n" +
	"\x0fGetMangaRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\"9\n" +
	"\x10GetMangaResponse\x12%\n" +
	"\x05manga\x18\x01 \x01(\v2\x0f.mangahub.MangaR\x05manga\"\x82\x01\n" +
	"\x12SearchMangaRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x9b\x01\n" +
	"\x13SearchMangaResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.mangahub.MangaR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x8c\x01\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"s\n" +
	"\x16UpdateProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ebroadcast_sent\x18\x03 \x01(\bR\rbroadcastSent2\xf2\x01\n" +
	"\fMangaService\x12A\n" +
	"\bGetManga\x12\x19.mangahub.GetMangaRequest\x1a\x1a.mangahub.GetMangaResponse\x12J\n" +
	"\vSearchManga\x12\x1c.mangahub.SearchMangaRequest\x1a\x1d.mangahub.SearchMangaResponse\x12S\n" +
	"\x0eUpdateProgress\x12\x1f.mangahub.UpdateProgressRequest\x1a .mangahub.UpdateProgressResponseB\x10Z\x0emangahub/protob\x06proto3"

var (
	file_proto_manga_service_proto_rawDescOnce sync.Once
	file_proto_manga_service_proto_rawDescData []byte
)

func file_proto_manga_service_proto_rawDescGZIP() []byte {
	file_proto_manga_service_proto_rawDescOnce.Do(func() {
		file_proto_manga_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_service_proto_rawDesc), len(file_proto_manga_service_proto_rawDesc)))
	})
	return file_proto_manga_service_proto_rawDescData
}

var file_proto_manga_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_manga_service_proto_goTypes = []any{
	(*Manga)(nil),                  // 0: mangahub.Manga
	(*UserProgress)(nil),           // 1: mangahub.UserProgress
	(*GetMangaRequest)(nil),        // 2: mangahub.GetMangaRequest
	(*GetMangaResponse)(nil),       // 3: mangahub.GetMangaResponse
	(*SearchMangaRequest)(nil),     // 4: mangahub.SearchMangaRequest
	(*SearchMangaResponse)(nil),    // 5: mangahub.SearchMangaResponse
	(*UpdateProgressRequest)(nil),  // 6: mangahub.UpdateProgressRequest
	(*UpdateProgressResponse)(nil), // 7: mangahub.UpdateProgressResponse
}
var file_proto_manga_service_proto_depIdxs = []int32{
	0, // 0: mangahub.GetMangaResponse.manga:type_name -> mangahub.Manga
	0, // 1: mangahub.SearchMangaResponse.data:type_name -> mangahub.Manga
	2, // 2: mangahub.MangaService.GetManga:input_type -> mangahub.GetMangaRequest
	4, // 3: mangahub.MangaService.SearchManga:input_type -> mangahub.SearchMangaRequest
	6, // 4: mangahub.MangaService.UpdateProgress:input_type -> mangahub.UpdateProgressRequest
	3, // 5: mangahub.MangaService.GetManga:output_type -> mangahub.GetMangaResponse
	5, // 6: mangahub.MangaService.SearchManga:output_type -> mangahub.SearchMangaResponse
	7, // 7: mangahub.MangaService.UpdateProgress:output_type -> mangahub.UpdateProgressResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_manga_service_proto_init() }
func file_proto_manga_service_proto_init() {
	if File_proto_manga_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_service_proto_rawDesc), len(file_proto_manga_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manga_service_proto_goTypes,
		DependencyIndexes: file_proto_manga_service_proto_depIdxs,
		MessageInfos:      file_proto_manga_service_proto_msgTypes,
	}.Build()
	File_proto_manga_service_proto = out.File
	file_proto_manga_service_proto_goTypes = nil
	file_proto_manga_service_proto_depIdxs = nil
}
